### ISSUE TITLE
Create read file functionality

### ISSUE THREAD

**Issue by iraklitchedia** [Rostlab/JS18_ProjectA_Group2#27]
Read dataset file using nodejs

**Comment by syxolk** [comment]
Please use the following downloads so you don't have to commit the files to git:

**core_dataset.csv**
- (70KB) https://js2018.blob.core.windows.net/kaggle/core_dataset.csv

**Indicators.csv**
- (48MB) https://js2018.blob.core.windows.net/kaggle/Indicators.csv.xz
- (110MB) https://js2018.blob.core.windows.net/kaggle/Indicators.csv.gz
- (120MB) https://js2018.blob.core.windows.net/kaggle/Indicators.csv.zip
