### ISSUE TITLE
plotly integration to boilerplate code

### ISSUE THREAD

**Issue by jyotirmay123** [Rostlab/JS18_ProjectA_Group2#4]

**Comment by iraklitchedia** [comment]
Plotly is integrated in project

**Comment by jyotirmay123** [comment]
@iraklitchedia Why did you close this??? The new set up is not yet integrated. So on what plotly got integrated?

**Comment by iraklitchedia** [comment]
@jyotirmay123  you can reopen the issue if it's not done yet

**Comment by jyotirmay123** [comment]
It is done, but nobody is merging my  push. What can I do. @iraklitchedia ..  Could you please do that for me??

**Comment by iraklitchedia** [comment]
@jyotirmay123  I approved your request

**Comment by jyotirmay123** [comment]
Integrated with new setup merged.
