### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by syxolk** [Rostlab/JS18_ProjectA_Group2#45]
Your `README.md` is out of date. Please add information on the following:
- How to install MySQL/MariaDB. What version is needed? How to configure the connection parameters (host, port, username, password)? How is the database initialized with tables and data?
- How to install and start RasaNLU. How to configure the connection parameters (host, port)?
- On which port is your API backend running? How to configure the connection parameters (host, port)?
- On which port is your frontend running? How to configure the port here?

How to run everything in development vs in production?

**Comment by syxolk** [comment]
Please resolve this.

**Comment by jyotirmay123** [comment]
Sorry for the delay..  We are working on to wrap up everything.. We will update README file soon. Thanks for reminding us.

**Comment by romikps** [comment]
Please close the issue in case the task is finished. Thanks

**Comment by syxolk** [comment]
Other missing information:
- What Python version is needed to run RasaNLU, 2 or 3?
- What needs to be installed by `pip`? Add a `requirements.txt` if possible.

**Comment by jyotirmay123** [comment]
Hi @syxolk, Updated README and codebase. Please try to deploy now. Let us know if any issue.
Please put mysql server creds for AZURE in config.sql. We are working on getting the same from environments, but for the time being, you can try deploying by putting them manually in server/config.js file.  Let us know the progress.

**Comment by jyotirmay123** [comment]
looks good with the current version of readme..
