### ISSUE TITLE
Error: Table exists, eventhough it does not

### ISSUE THREAD

**Issue by csehlke** [Rostlab/JS18_ProjectA_Group2#63]
I set up a plain database, uploaded the core data set without problems and then wanted to upload the second data set and I got an `Error: Table with Indicators.csv exist in the database! Please upload csv with different name.` 

I checked the database: there is only the config and the core_data table
and it does not appear in the dropdown in the UI

**Comment by csehlke** [comment]
are we saving the list of uploaded tables somewhere else than the database? now I also encountered the problem with the core_dataset

**Comment by csehlke** [comment]
maybe we could just check in the database if a table with the same name already exists and then add an incrementing number to the name

I think multi-upload of the same file should be allowed, in case something went wrong (for example due to the internet connection) the first time

**Comment by iraklitchedia** [comment]
It checks the files in the server/data folder, if there exists .csv file with same name, then it wont create new file and new table in database.

**Comment by iraklitchedia** [comment]
I guess your problem was that you had core_dataset.csv and indicators.csv file in that folder that's why you got an error
