### ISSUE TITLE
Enhancement for showing the column names

### ISSUE THREAD

**Issue by csehlke** [Rostlab/JS18_ProjectA_Group2#64]
On my screen they are cut of at the edges.
So maybe
- add some spacing
- and put a label that says that those are the column names

**Comment by iraklitchedia** [comment]
Yes, you can enhance column names view

**Comment by jyotirmay123** [comment]
@csehlke Could you please put a screen shot of the issue for better understanding?

**Comment by csehlke** [comment]
![grafik](https://user-images.githubusercontent.com/29836078/38411996-a4c931dc-3988-11e8-873d-2a71ca1e8b0a.png)
but only in fullscreen mode and then there is a scroll bar with which it is possible to show the right side but still not the left side

Found another piont to improve:
- dismiss the first column `primKey`

**Comment by jyotirmay123** [comment]
Okay..  It comes fine in my system. But still, you can try putting some margin in .css file for this component.

**Comment by jyotirmay123** [comment]
Removed primKey.

**Comment by csehlke** [comment]
I removed the `primKey` and added some space on the right and left side of the column names

Now only a label might be missing

**Comment by iraklitchedia** [comment]
@csehlke I can add label if no one started doing it already
