### ISSUE TITLE
NULL values in dob column that should not be there due to wrong date interpretation

### ISSUE THREAD

**Issue by csehlke** [Rostlab/JS18_ProjectA_Group2#65]
I uploaded the core_data set via UI upload and then took a look at the data:

The column `dob` has a lot of NULL values that should not be there.

This always happens when the date in the csv file is not in the format `mm/dd/yyyy`. 
In the csv file leading zeros are not stored, so that a possible format could also be `m/d/yyyy`.

![grafik](https://user-images.githubusercontent.com/29836078/38383104-e32811c8-390b-11e8-8436-949d02b03044.png)

**Comment by iraklitchedia** [comment]
I am working to fix this

**Comment by iraklitchedia** [comment]
Fixed
