### ISSUE TITLE
Enhancement: order of storing the data in the database

### ISSUE THREAD

**Issue by csehlke** [Rostlab/JS18_ProjectA_Group2#66]
we are first adding the table to the database and then adding it to the config table.
would it not make more sense to add it in the config table first and then create the table in case creating the table does not work? Because then in the end we do not know which table name is already used.

Maybe we should add a column uploadFinished that gets edited after everything finished

**Comment by jyotirmay123** [comment]
We cannot add it to config first as we are generating reverse-mapping json string from uploaded table and storing it to config with tablename later. 
Yes, there may be some validation added.
