### ISSUE TITLE
Database inconsistency after redeployment

### ISSUE THREAD

**Issue by csehlke** [Rostlab/JS18_ProjectA_Group2#70]
When the csv file is removed from the server/data folder (for example due to a new deployment), it is possible to upload the same data again, eventhough there is already a table in the database with the same name.

The result is then: no new table gets added in the database, the old one does not get altered, but there is a new (identical) entry in the config table which results in the UI showing the tabe twice.

I do not know if there is an easy fix to it, maybe we need to check in the database before uploading, but that is a bigger task. Any other Ideas?

**Comment by iraklitchedia** [comment]
We don't wanted to waste to much time on the task which was already additional feature. So, in my opinion the way it is now is OK.
