### ISSUE TITLE
I am happy that nice people like you offer a free sql server for #SqlBingo

### ISSUE THREAD

**Issue by Phibedy** [Rostlab/JS18_ProjectA_Group2#88]
We have to play sql bingo 💃 
There are two rules:
* You say a table name and I will remove it 
* I will randomly add, remove or modify tables and you can find out what I did

Two outcomes:
* I win if you remove the password from your public repository 👍 
* You lose if I accidentally format your database 👎 

Hint: https://github.com/Rostlab/JS18_ProjectA_Group2/blob/develop/server/config.js

**Comment by shayansiddiqui** [comment]
Thanks for pointing out. It was done accidentally from the dev environment. And yes obviously we have lost the game.

**Comment by Phibedy** [comment]
You are welcome :)
Edit:
https://github.com/Rostlab/JS18_ProjectA_Group2/commit/67d37c1b088a25ecf016351d7dd7d490f6420f70 still shows the password I hope you changed it :)
